services:
    AppBundle\Controller\MainController:
        arguments:
            $projectRepository: "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:Project')"

    AppBundle\DataFixtures\AppFixtures:
        tags: ['doctrine.fixture.orm']
    app.task.import_project:
        class: AppBundle\Task\ImportProjectTask
        arguments:
            $entityManager: "@doctrine.orm.entity_manager"
            $githubOAuthToken: "%app.github.token%"
            $kilnOAuthToken: "%app.kiln.token%"
