services:
    app.controller.main:
        class: AppBundle\Controller\MainController
        arguments:
            $projectRepository: "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:Project')"
            $formFactory: "@form.factory"

    app.controller.webhook:
        class: AppBundle\Controller\WebhookController
        arguments:
            $importProjectTask: "@app.task.import_project"

    app.fixtures:
        class: AppBundle\DataFixtures\AppFixtures
        tags: ['doctrine.fixture.orm']

    app.task.import_project:
        class: AppBundle\Task\ImportProjectTask
        arguments:
            $entityManager: "@doctrine.orm.entity_manager"
            $githubOAuthToken: "%app.github.token%"
            $kilnOAuthToken: "%app.kiln.token%"

    app.command.import_project:
        class: AppBundle\Command\ImportProjectCommand
        arguments:
            $importProjectTask: "@app.task.import_project"
        tags:
            - { name: "console.command" }

    app.form.type.datalist_type:
        class: AppBundle\Form\Type\DatalistType
        tags:
            -  { name: form.type, alias: datalist }
