services:
    AppBundle\Controller\MainController:
        arguments:
            $projectRepository: "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:Project')"

    AppBundle\DataFixtures\AppFixtures:
        tags: ['doctrine.fixture.orm']
