imports:
    - { resource: config.yml }
    - { resource: ../vendor/webfactory/symfony-default-config/config_development.yml }
    - { resource: ../vendor/webfactory/doctrine-bundle-default-config/config_development.yml }
    - { resource: ../vendor/webfactory/monolog-bundle-default-config/config_development.yml }
