imports:
    - { resource: config.yml }
    - { resource: ../vendor/webfactory/doctrine-bundle-default-config/config_production.yml }
    - { resource: ../vendor/webfactory/monolog-bundle-default-config/config_production.yml }
