imports:
    - { resource: ../app/config/parameters.yml }
    - { resource: ../vendor/webfactory/symfony-default-config/config.yml }
    - { resource: ../vendor/webfactory/doctrine-bundle-default-config/config.yml }

parameters:
    app.kiln.token: '%env(KILN_OAUTH_TOKEN)%'
    env(KILN_OAUTH_TOKEN): # default is null, set this environment variable on your server to communicate with repositories on Kiln
    app.github.token: '%env(GITHUB_OAUTH_TOKEN)%'
    env(GITHUB_OAUTH_TOKEN): # default is null, set this environment variable on your server to communicate with private repositories on GitHub
